-- Product URLs Reference
-- These are the product page URLs provided by the user
-- We need DIRECT IMAGE URLs (not product page URLs) to update the image_url column

-- Product Page URLs (for reference):
-- 1. iPhone 15 Pro: https://www.apple.com/in/iphone-15-pro/
-- 2. Samsung Galaxy S24 Ultra: https://www.samsung.com/in/smartphones/galaxy-s24-ultra/
-- 3. Nike Air Max 270: https://www.nike.com/in/w/air-max-270-shoes-5ix6dzy7ok
-- 4. MacBook Pro M3: https://www.apple.com/in/shop/buy-mac/macbook-pro
-- 5. Tesla Model Y: https://www.tesla.com/modely
-- 6. Google Pixel 8 Pro: https://store.google.com/product/pixel_8_pro
-- 7. Microsoft Surface Laptop 5: https://www.microsoft.com/en-us/surface
-- 8. Sony WH-1000XM5: https://www.sony.co.in/electronics/headband-headphones/wh-1000xm5
-- 9. Adidas Ultraboost 22: https://www.adidas.co.in
-- 10. iPad Pro 12.9": https://www.apple.com/in/ipad-pro/
-- 11. iPhone 15: https://www.apple.com/in/iphone-15/
-- 12. Samsung Galaxy S23 Ultra: https://www.samsung.com/in/smartphones/galaxy-s23-ultra/
-- 13. OnePlus 12: https://www.oneplus.com/global/oneplus-12
-- 14. Xiaomi 14 Pro: https://www.mi.com/global/product/xiaomi-14-pro
-- 15. Nothing Phone 2: https://nothing.tech/phone-2
-- 16. Dell XPS 15: https://www.dell.com/en-in/shop/laptops/xps-15-9530-laptop/spd/xps-15-9530-laptop
-- 17. HP Spectre x360: https://www.hp.com/in-en/shop/collections/spectre
-- 18. Lenovo ThinkPad X1 Carbon: https://www.lenovo.com/in/en/laptops/thinkpad/thinkpad-x1/
-- 19. ASUS ROG Zephyrus G14: https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-g14-series/
-- 20. Razer Blade 15: https://www.razer.com/gaming-laptops/razer-blade
-- 21. AirPods Pro 2: https://www.apple.com/in/airpods-pro/
-- 22. Bose QuietComfort 45: https://www.bose.co.in/en_in/products/headphones/over_ear_headphones/quietcomfort-45.html
-- 23. Sennheiser Momentum 4: https://www.sennheiser.com/momentum-4-wireless/
-- 24. JBL Flip 6: https://www.jbl.com/portable-speakers/FLIP+SERIES/
-- 25. Nike Air Force 1: https://www.nike.com/in/w/air-force-1-shoes-3n82yznik1
-- 26. Adidas Stan Smith: https://www.adidas.co.in/stan_smith
-- 27. New Balance 990v5: https://www.newbalance.com
-- 28. Vans Old Skool: https://www.vans.in/shop/en/vans-in/men-shoes-old-skool
-- 29. Samsung Galaxy Tab S9: https://www.samsung.com/in/tablets/galaxy-tab-s9/
-- 30. iPad Air: https://www.apple.com/in/ipad-air/
-- 31. Tesla Model 3: https://www.tesla.com/model3
-- 32. Ford F-150 Lightning: https://www.ford.com/trucks/f150/f150-lightning/
-- 33. Apple Watch Series 9: https://www.apple.com/in/apple-watch-series-9/
-- 34. Samsung Galaxy Watch 6: https://www.samsung.com/in/wearables/galaxy-watch6/
-- 35. Garmin Fenix 7: https://www.garmin.com/en-IN/p/102913
-- 36. iPhone 14: https://www.apple.com/in/iphone-14/
-- 37. Samsung Galaxy A54: https://www.samsung.com/in/smartphones/galaxy-a54-5g/
-- 38. Motorola Edge 40: https://www.motorola.in/smartphones-motorola-edge-40/p
-- 39. Realme GT 5: https://www.realme.com/global/realme-gt-5
-- 40. MacBook Air M2: https://www.apple.com/in/macbook-air-m2/
-- 41. Dell Inspiron 15: https://www.dell.com/en-in/shop/laptops/inspiron-15-laptops/sr/laptops/inspiron-15
-- 42. Acer Predator Helios: https://www.acer.com/ac/en/US/content/predator-model/
-- 43. MSI Stealth 16: https://www.msi.com/Laptop/Stealth-16-Series
-- 44. Sony WF-1000XM5: https://www.sony.co.in/electronics/truly-wireless/wf-1000xm5
-- 45. Apple AirPods 3: https://www.apple.com/in/airpods/
-- 46. Beats Studio Pro: https://www.beatsbydre.com/headphones/studio-pro
-- 47. Nike Dunk Low: https://www.nike.com/in/w/dunk-low-shoes-8g1epznik1
-- 48. Adidas Yeezy 350: https://www.adidas.co.in/yeezy
-- 49. Puma RS-X: https://in.puma.com/in/en/pd/rs-x-series/
-- 50. iPad Mini: https://www.apple.com/in/ipad-mini/
-- 51. Microsoft Surface Pro 9: https://www.microsoft.com/en-us/surface/devices/surface-pro-9

